export const FETCH_STRIPPING = 'FETCH_STRIPPING';
export const UPDATE_MODAL_STRIPPING = 'UPDATE_MODAL_STRIPPING';
export const SET_STRIPPING = 'SET_STRIPPING';

export const SAVE_STRIPPING = 'SAVE_STRIPPING';
export const UPDATE_STRIPPING = 'UPDATE_STRIPPING';
export const DELETE_STRIPPING = 'DELETE_STRIPPING';