export const FETCH_REVISION_YEAR = 'FETCH_REVISION_YEAR';
export const STORE_REVISION_YEAR = 'STORE_REVISION_YEAR';
export const UPDATE_REVISION_YEAR= 'UPDATE_REVISION_YEAR';
export const DELETE_REVISION_YEAR= 'DELETE_REVISION_YEAR';

export const SET_REVISION_YEAR_FAAS= 'SET_REVISION_YEAR_FAAS';
export const SET_REVISION_YEAR= 'SET_REVISION_YEAR';
