export const FETCH_VARIABLE= 'FETCH_VARIABLE';
export const STORE_VARIABLE =  'STORE_VARIABLE';
export const UPDATE_VARIABLE = 'UPDATE_VARIABLE';
export const DELETE_VARIABLE = 'DELETE_VARIABLE';

export const SAVE_EXPRESSION = 'SAVE_EXPRESSION';
export const REMOVE_EXPRESSION = 'REMOVE_EXPRESSION';
