export const FETCH_PERSONNEL = 'FETCH_PERSONNEL';
export const STORE_PERSONNEL = 'STORE_PERSONNEL';
export const UPDATE_PERSONNEL= 'UPDATE_PERSONNEL';
export const DELETE_PERSONNEL= 'DELETE_PERSONNEL';
