export const FETCH_MULTIPLE = 'FETCH_MULTIPLE';
export const STORE_MULTIPLE =  'STORE_MULTIPLE';
export const UPDATE_MULTIPLE = 'UPDATE_MULTIPLE';
export const DELETE_MULTIPLE= 'DELETE_MULTIPLE';
export const DELETE_MULTIPLE_MULTIPLE = 'DELETE_MULTIPLE_MULTIPLE';