export const GET_MUNICIPALITY_CITY = 'GET_MUNICIPALITY_CITY';
export const SAVE_MUNICIPALITY_CITY =  'SAVE_MUNICIPALITY_CITY';
export const UPDATE_MUNICIPALITY_CITY = 'UPDATE_MUNICIPALITY_CITY';
export const DELETE_MUNICIPALITY_CITY = 'DELETE_MUNICIPALITY_CITY';
export const UPDATE_MODAL = 'UPDATE_MODAL';
export const GET_BARANGAY = 'GET_BARANGAY';