export const FETCH_INDIVIDUALS = 'FETCH_INDIVIDUALS';
export const STORE_INDIVIDUALS =  'STORE_INDIVIDUALS';
export const UPDATE_INDIVIDUALS = 'UPDATE_INDIVIDUALS';
export const DELETE_INDIVIDUALS = 'DELETE_INDIVIDUALS';
export const DELETE_MULTIPLE_INDIVIDUALS = 'DELETE_MULTIPLE_INDIVIDUALS';