export const FETCH_CLASSIFICATION = 'FETCH_CLASSIFICATION';
export const STORE_CLASSIFICATION =  'STORE_CLASSIFICATION';
export const UPDATE_CLASSIFICATION = 'UPDATE_CLASSIFICATION';
export const DELETE_CLASSIFICATION = 'DELETE_CLASSIFICATION';

export const UPDATE_MODAL_CLASSIFICATION = 'UPDATE_MODAL_CLASSIFICATION';