export const FETCH_LAND_ADJUSTMENT = 'FETCH_LAND_ADJUSTMENT';
export const STORE_LAND_ADJUSTMENT =  'STORE_LAND_ADJUSTMENT';
export const UPDATE_LAND_ADJUSTMENT = 'UPDATE_LAND_ADJUSTMENT';
export const DELETE_LAND_ADJUSTMENT = 'DELETE_LAND_ADJUSTMENT';
export const ADD_CLASSIFICATION = 'ADD_CLASSIFICATION';
export const UPDATE_MODAL_LAND_ADJUSTMENT = 'UPDATE_MODAL_LAND_ADJUSTMENT';
