export const FETCH_LAND_ADJUSTMENT = 'FETCH_LAND_ADJUSTMENT';
export const STORE_LAND_ADJUSTMENT =  'STORE_LAND_ADJUSTMENT';
export const UPDATE_LAND_ADJUSTMENT = 'UPDATE_LAND_ADJUSTMENT';
export const DELETE_LAND_ADJUSTMENT = 'DELETE_LAND_ADJUSTMENT';

export const ADD_CLASSIFICATION = 'ADD_CLASSIFICATION';
export const REMOVE_CLASSIFICATION = 'REMOVE_CLASSIFICATION';
export const REMOVE_ALL_CLASSIFICATION = 'REMOVE_ALL_CLASSIFICATION';
export const UPDATE_MODAL_LAND_ADJUSTMENT = 'UPDATE_MODAL_LAND_ADJUSTMENT';

export const SET_SELECTED_ADJUSTMENT = 'SET_SELECTED_ADJUSTMENT';
export const REMOVE_SELECTED_ADJUSTMENT = 'REMOVE_SELECTED_ADJUSTMENT';
