export const FETCH_JOB_POSITION = 'FETCH_JOB_POSITION';
export const STORE_JOB_POSITION = 'STORE_JOB_POSITION';
export const UPDATE_JOB_POSITION = 'UPDATE_JOB_POSITION';
export const DELETE_JOB_POSITION = 'DELETE_JOB_POSITION';
