export const SET_MARKET_VALUE = 'SET_MARKET_VALUE';

export const STORE_MARKET_VALUE = 'STORE_MARKET_VALUE';
export const UPDATE_MARKET_VALUE = 'UPDATE_MARKET_VALUE';
export const DELETE_MARKET_VALUE = 'DELETE_MARKET_VALUE';