export const FETCH_ASSESSMENT_LEVEL = 'FETCH_ASSESSMENT_LEVEL';
export const STORE_ASSESSMENT_LEVEL =  'STORE_ASSESSMENT_LEVEL';
export const UPDATE_ASSESSMENT_LEVEL = 'UPDATE_ASSESSMENT_LEVEL';
export const DELETE_ASSESSMENT_LEVEL = 'DELETE_ASSESSMENT_LEVEL';

export const SET_ASSESSMENT_LEVEL_ID = 'SET_ASSESSMENT_LEVEL_ID';

