export const FETCH_SUB_CLASS = 'FETCH_SUB_CLASS';
export const UPDATE_MODAL_SUB_CLASS = 'UPDATE_MODAL_SUB_CLASS';

export const SAVE_SUB_CLASS = 'SAVE_SUB_CLASS';
export const UPDATE_SUB_CLASS = 'UPDATE_SUB_CLASS';
export const DELETE_SUB_CLASS = 'DELETE_SUB_CLASS';