export const FETCH_SPECIFIC_CLASS = 'FETCH_SPECIFIC_CLASS';
export const UPDATE_MODAL_SPECIFIC_CLASS = 'UPDATE_MODAL_SPECIFIC_CLASS';

export const SAVE_SPECIFIC_CLASS = 'SAVE_SPECIFIC_CLASS';
export const UPDATE_SPECIFIC_CLASS = 'UPDATE_SPECIFIC_CLASS';
export const DELETE_SPECIFIC_CLASS = 'DELETE_SPECIFIC_CLASS';