export const FETCH_SPECIFIC_CLASS = 'FETCH_SPECIFIC_CLASS';
export const UPDATE_MODAL_SPECIFIC_CLASS = 'UPDATE_MODAL_SPECIFIC_CLASS';
export const SET_SPECIFIC_CLASS = 'SET_SPECIFIC_CLASS';

export const SAVE_SPECIFIC_CLASS = 'SAVE_SPECIFIC_CLASS';
export const UPDATE_SPECIFIC_CLASS = 'UPDATE_SPECIFIC_CLASS';
export const DELETE_SPECIFIC_CLASS = 'DELETE_SPECIFIC_CLASS';

export const REMOVE_SPECIFIC_CLASS = 'REMOVE_SPECIFIC_CLASS';