export const FETCH_BARANGAY = 'SET_BARANGAY';
export const CLEAR_BARANGAY = 'CLEAR_BARANGAY';
export const SET_MUNICIPALITY_DATA = 'SET_MUNICIPALITY_DATA';
export const UPDATE_MODAL_BARANGAY = 'UPDATE_MODAL_BARANGAY';

export const SAVE_BARANGAY = 'SAVE_BARANGAY';
export const UPDATE_BARANGAY = 'UPDATE_BARANGAY';
export const DELETE_BARANGAY = 'DELETE_BARANGAY';