export const FETCH_JURIDICALS = 'FETCH_JURIDICALS';
export const STORE_JURIDICALS =  'STORE_JURIDICALS';
export const UPDATE_JURIDICALS = 'UPDATE_JURIDICALS';
export const DELETE_JURIDICALS = 'DELETE_JURIDICALS';
export const DELETE_MULTIPLE_JURIDICALS = 'DELETE_MULTIPLE_JURIDICALS';